#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t handsonpinns \
                         -C "start_jupyter -t -T @tool PINNs_V1-1.ipynb" \
                         -u anaconda-7 \
                         -w headless \
                         -r none
